# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='votes',
            new_name='confience',
        ),
    ]
